// <auto-generated />
namespace Infraestructura.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Nuevassemillasdeusuarioyempleado : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Nuevassemillasdeusuarioyempleado));
        
        string IMigrationMetadata.Id
        {
            get { return "202107270100425_Nuevas semillas de usuario y empleado"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
