// <auto-generated />
namespace Infraestructura.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class RealacionFormaPago_MovimientoCuentaCorriente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RealacionFormaPago_MovimientoCuentaCorriente));
        
        string IMigrationMetadata.Id
        {
            get { return "202108041554596_Realacion FormaPago_MovimientoCuentaCorriente"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
