// <auto-generated />
namespace Infraestructura.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class actualizar_configuracion_para_arqueo_negativo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(actualizar_configuracion_para_arqueo_negativo));
        
        string IMigrationMetadata.Id
        {
            get { return "202105022157295_actualizar_configuracion_para_arqueo_negativo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
