// <auto-generated />
namespace Infraestructura.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class inicio_sistema_desde_cero : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inicio_sistema_desde_cero));
        
        string IMigrationMetadata.Id
        {
            get { return "202103050223059_inicio_sistema_desde_cero"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
